# Generated by Django 4.2.3 on 2023-07-13 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('files', models.FileField(blank=True, null=True, upload_to='files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('TANKI', 'Танки'), ('HILY', 'Хилы'), ('DD', 'ДД'), ('TORGOVCI', 'Торговцы'), ('GILDMASTERI', 'Гилдмастеры'), ('KVESTGIVERI', 'Квестгиверы'), ('KUZNECI', 'Кузнецы'), ('KOZHEVNIKI', 'Кожевники'), ('ZELEVARI', 'Зельевары'), ('MASTERA_ZAKLINANIY', 'Мастера заклинаний')], max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisement')),
            ],
        ),
    ]
